export const postTypes = {
  CREATE_SESSION: "CREATE_SESSION",
  GET_PRODUCTS: "GET_PRODUCTS",
  GET_CART: "GET_CART",
  SET_CART: "SET_CART",
  GET_PRODUCTS_BY_CART: "GET_PRODUCTS_BY_CART",
  SEARCH_PRODUCTS: "SEARCH_PRODUCTS"
}
